# Generated by Django 3.0.7 on 2020-07-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beauty',
            new_name='Brand',
        ),
    ]
