# Generated by Django 3.0.7 on 2020-07-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(verbose_name='purchase date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.CharField(choices=[('S', 'Skincare'), ('M', 'Makeup'), ('A', 'Accessory')], default='S', max_length=1),
        ),
    ]
