# Generated by Django 3.0.7 on 2020-07-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200703_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='item',
            new_name='category',
        ),
    ]
