# Generated by Django 3.0.7 on 2020-07-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(to='main_app.Product'),
        ),
    ]
